### ISSUE TITLE
YAML anchors and aliases.

### ISSUE THREAD

**Issue by philomory** [HipByte/motion-yaml#2]
motion-yaml seems to choke on the use of anchors and aliases:

All of the following fail:

```yaml
# Scalars
test_anchor_scalar: &scalar_test
test_alias_scalar: *scalar_test
```

```yaml
# Maps
test_anchor_map: &map_test
  a: 1
  b: 2
test_alias_map: *map_test
```

```yaml
# Sequences
test_anchor_sequence: &sequence_test
  - a
  - b
test_alias_sequence: *sequence_test
```

```yaml
# Scalars inside a sequence
sequence_with_anchor_and_alias:
  - 'hello'
  - &test_inside_sequence 'test'
  - *test_inside_sequence
  - 'goodbye'
```

They fail on their own, and they fail when they are included with other yaml data. In some cases, they actually mangle the structure of the surrounding data (particularly the maps), while in other cases they just silently disappear.

I'm unsure whether this is a failure in motion-yaml or in the underlying YAMLKit. In the absence of a solution I am attempting to find a pure-ruby YAML implementation I can use.
